# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xa7a35tcpg236-1I

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Monster/Desktop/project_LASTBER/project_LASTBER.cache/wt [current_project]
set_property parent.project_path C:/Users/Monster/Desktop/project_LASTBER/project_LASTBER.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Monster/Desktop/project_LASTBER/project_LASTBER.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  {C:/Users/Monster/Desktop/YETHEERRRAMKYETEERR/LabProjec t/LabProjec t.srcs/sources_1/new/subtractor.sv}
  {C:/Users/Monster/Desktop/YETHEERRRAMKYETEERR/LabProjec t/LabProjec t.srcs/sources_1/new/adder.sv}
  {C:/Users/Monster/Desktop/YETHEERRRAMKYETEERR/LabProjec t/LabProjec t.srcs/sources_1/new/registerFile.sv}
  {C:/Users/Monster/Desktop/YETHEERRRAMKYETEERR/LabProjec t/LabProjec t.srcs/sources_1/new/mux2.sv}
  {C:/Users/Monster/Desktop/YETHEERRRAMKYETEERR/LabProjec t/LabProjec t.srcs/sources_1/new/ALU.sv}
  C:/Users/Monster/Desktop/project_LASTBER/project_LASTBER.srcs/sources_1/new/mainDecoder.sv
  {C:/Users/Monster/Desktop/YETHEERRRAMKYETEERR/LabProjec t/LabProjec t.srcs/sources_1/new/datapath.sv}
  {C:/Users/Monster/Desktop/YETHEERRRAMKYETEERR/LabProjec t/LabProjec t.srcs/sources_1/new/selecter.sv}
  {C:/Users/Monster/Desktop/YETHEERRRAMKYETEERR/LabProjec t/LabProjec t.srcs/sources_1/new/dataMemory.sv}
  {C:/Users/Monster/Desktop/YETHEERRRAMKYETEERR/LabProjec t/LabProjec t.srcs/sources_1/new/SevSeg_4Digit.sv}
  {C:/Users/Monster/Desktop/YETHEERRRAMKYETEERR/LabProjec t/LabProjec t.srcs/sources_1/new/instructionMemory.sv}
  {C:/Users/Monster/Desktop/YETHEERRRAMKYETEERR/LabProjec t/LabProjec t.srcs/sources_1/new/singleCyleProcessor.sv}
  {C:/Users/Monster/Desktop/YETHEERRRAMKYETEERR/LabProjec t/LabProjec t.srcs/sources_1/new/programCounter.sv}
  {C:/Users/Monster/Desktop/YETHEERRRAMKYETEERR/LabProjec t/LabProjec t.srcs/sources_1/new/debounce.sv}
  {C:/Users/Monster/Desktop/YETHEERRRAMKYETEERR/LabProjec t/LabProjec t.srcs/sources_1/new/topDesign.sv}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Monster/Desktop/YETHEERRRAMKYETEERR/LabProjec t/LabProjec t.srcs/constrs_1/new/cons.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Monster/Desktop/YETHEERRRAMKYETEERR/LabProjec t/LabProjec t.srcs/constrs_1/new/cons.xdc}}]


synth_design -top topDesign -part xa7a35tcpg236-1I


write_checkpoint -force -noxdef topDesign.dcp

catch { report_utilization -file topDesign_utilization_synth.rpt -pb topDesign_utilization_synth.pb }
